apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-jpqvgktk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-jpqvgktk:azure-c809b71a1b4b26977dcefa49342201256589f754
          name: container-image
